[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tethered_planning"
dynamic = ["version"]
description = "Motion planning algorithms for tethered mobile robots."
authors = [
    {name="Gianpietro Battocletti", email="g.battocletti@tudelft.nl"},
]
readme = "README.md"
keywords = [
    "tethered robot",
    "mobile robot",
    "path planning",
]
dependencies = [
    "numpy",
    "matplotlib",
    "shapely",
    "openpyxl",
    "PyYAML",
    "typing-extensions",
    "plotly",
    "kaleido",
    "networkx",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "pytest",
    "snakeviz",
]

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools.dynamic]
version = {attr = "tethered_planning.__version__"}

[tool.black]
line-length = 88
exclude = 'dev/.*'

[tool.isort]
profile = "black"
py_version = 311
line_length = 88
skip = ["dev/.*"]

[tool.license]
name = "GNU General Public License v3.0"
url = "https://www.gnu.org/licenses/gpl-3.0.en.html"
