# Settings Default

## General settings
sim_folder: ""
sim_id: ""
sim_name: ""
env_name: "env_default"
fix_seed: false
seed: 0
    
## Planner settings
planner:
    name: "rrt_star"

    # RRT settings
    max_edge_length: 0.2
    goal_bias: false
    goal_bias_rate: 0.1
    goal_reached_termination_condition: false
    max_nodes_n_termination_condition: true
    max_nodes_n: 1000

    # Triangulation settings
    search_algorithm: "a_star"
