# Settings Default

## General settings
sim_folder: ""
sim_id: ""
sim_name: ""
env_name: "env_default"
fix_seed: false
seed: 0
    
## Planner settings
planner:
    name: "rrt_star"

    # RRT settings
    max_edge_length: 0.2
    goal_bias: false
    goal_bias_rate: 0.1
    goal_reached_termination_condition: false
    max_nodes_n_termination_condition: true
    max_nodes_n: 100

    # Triangulation settings
    search_algorithm: "a_star"

## Plot and animation settings
plot:
    # general settings
    show: false
    save: false

    # figure settings
    figsize: [9, 6]  # [width, height] in inches
    dpi: 300
    format: "png"
    title: ""
    x_label: "x"
    y_label: "y"
    show_legend: false

    node_size: 4
    edge_alpha: 0.8

# Animation settings
anim:
    # general settings
    animate: true
    show: false
    save: true

    # figure settings
    anim_title: ""
    time_step: 50
    speed_up_factor: 10